name: weather
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  envied: ^0.2.3
  flutter_riverpod: ^2.0.2
  json_annotation: ^4.7.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  carousel_slider: ^4.1.1
  go_router: ^5.1.1
  dartz: ^0.10.1
  geolocator: ^9.0.2
  flutter_overlay_loader: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.3
  build_runner: ^2.3.2
  envied_generator: ^0.2.3
  hive_generator: ^2.0.0

dependency_overrides:
  analyzer: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/cities/
